// Code generated by tygo. DO NOT EDIT.
// Source: veto-core/config/analytics.go
// Regenerate: cd veto-core/config && go run github.com/gzuidhof/tygo@latest generate

/**
 * AnalyticsResponse is the body returned by /internal/v1/me/analytics.
 * veto-web aliases this as AnalyticsData for backward source compat.
 */
export interface AnalyticsResponse {
  period_start: string;
  period_end: string;
  total_requests: number /* int64 */;
  actions: ActionsBlock;
  findings: FindingCount[] | null;
  total_findings: number /* int64 */;
  top_rules: RuleCount[] | null;
  total_rules_seen: number /* int */;
  latency_ms: LatencyPercentile;
  daily_volume: DayCount[] | null;
}
export interface ActionsBlock {
  allow: number /* int64 */;
  block: number /* int64 */;
  redact: number /* int64 */;
}
export interface FindingCount {
  category: string;
  count: number /* int64 */;
}
export interface RuleCount {
  rule: string;
  count: number /* int64 */;
  category: string;
}
export interface LatencyPercentile {
  p50: number /* int */;
  p95: number /* int */;
  p99: number /* int */;
}
export interface DayCount {
  date: string; // YYYY-MM-DD UTC
  count: number /* int64 */;
}
