// Code generated by tygo. DO NOT EDIT.
// Regenerate: cd veto-core/config && make codegen

//////////
// source: analytics.go

/**
 * AnalyticsResponse is the body returned by /internal/v1/me/analytics.
 * veto-web aliases this as AnalyticsData for backward source compat.
 */
export interface AnalyticsResponse {
  period_start: string;
  period_end: string;
  total_requests: number /* int64 */;
  actions: ActionsBlock;
  findings: FindingCount[];
  total_findings: number /* int64 */;
  top_rules: RuleCount[];
  total_rules_seen: number /* int */;
  latency_ms: LatencyPercentile;
  daily_volume: DayCount[];
}
export interface ActionsBlock {
  allow: number /* int64 */;
  block: number /* int64 */;
  redact: number /* int64 */;
}
export interface FindingCount {
  category: string;
  count: number /* int64 */;
}
export interface RuleCount {
  rule: string;
  count: number /* int64 */;
  category: string;
}
export interface LatencyPercentile {
  p50: number /* int */;
  p95: number /* int */;
  p99: number /* int */;
}
export interface DayCount {
  date: string; // YYYY-MM-DD UTC
  count: number /* int64 */;
}
